[package]
name = "gh-starpilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.18", features = ["derive"] }
predicates = "3.1.2"
